-- Insert key BDD scenarios from the test database
-- Epic 1: Color Contrast Compliance
INSERT INTO bdd_test_scenarios (epic_number, epic_name, scenario_number, scenario_title, given_context, when_action, then_outcome, additional_expectations, status, priority, implementation_location, test_coverage_method) VALUES
(1, 'Color Contrast Compliance', '1.1', 'Training type descriptions meet 4.5:1 contrast ratio', 'a user views the training options on the assessment page', 'they read the training type descriptions', 'the text should have a contrast ratio of at least 4.5:1 against the background', 'the text should be readable in both light and dark modes', 'PASSED', 'P0', '/client/src/index.css', 'Manual visual inspection + color contrast analyzer'),
(1, 'Color Contrast Compliance', '1.2', 'Input placeholders meet 4.5:1 contrast ratio', 'a user views form inputs on the assessment page', 'they see placeholder text in empty fields', 'the placeholder text should have a contrast ratio of at least 4.5:1', 'the placeholders should be readable in both light and dark modes', 'PASSED', 'P0', '/client/src/index.css', 'Manual visual inspection in both themes');

-- Epic 11: Training Option Configuration
INSERT INTO bdd_test_scenarios (epic_number, epic_name, scenario_number, scenario_title, given_context, when_action, then_outcome, additional_expectations, status, priority, implementation_location, test_coverage_method, expected_values) VALUES
(11, 'Training Option Configuration', '11.2', 'Half Day Workshop focuses on #1 critical area', 'a user selects "Half Day Workshop" as their training type', 'they complete the assessment and view results', 'they should see: Training cost: $2,000, Duration: 4 hours, Focus: Only the #1 highest priority driver', 'recommendations should be filtered to show only that driver AND ROI should be calculated based on improving 1/7 of the gap', 'PASSED', 'P0', '/client/src/lib/trainingRecommendations.ts', 'Code review + mathematical verification', 'Cost: $2000, focusAreas: 1'),
(11, 'Training Option Configuration', '11.3', 'Full Day Workshop focuses on top 2 critical areas', 'a user selects "Full Day Workshop" as their training type', 'they complete the assessment and view results', 'they should see: Training cost: $3,500, Duration: 8 hours, Focus: Top 2 highest priority drivers', 'recommendations should be filtered to show only those 2 drivers AND ROI should be calculated based on improving 2/7 of the gap', 'PASSED', 'P0', '/client/src/lib/trainingRecommendations.ts', 'Code review + mathematical verification', 'Cost: $3500, focusAreas: 2');

-- Epic 14: ROI Calculation Logic
INSERT INTO bdd_test_scenarios (epic_number, epic_name, scenario_number, scenario_title, given_context, when_action, then_outcome, additional_expectations, status, priority, implementation_location, test_coverage_method, expected_values) VALUES
(14, 'ROI Calculation Logic', '14.1', 'ROI calculated using gap-based improvement model', 'a user completes an assessment with specific scores', 'the system calculates ROI', 'it should use this formula: totalGap = 0.85 - currentReadiness, improvementPerDriver = totalGap / 7, totalImprovement = improvementPerDriver × focusAreas, currentDysfunction = 1 - currentReadiness, projectedSavings = annualCostOfDysfunction × (totalImprovement / currentDysfunction), roi = (projectedSavings - trainingCost) / trainingCost', NULL, 'PASSED', 'P0', '/client/src/lib/trainingRecommendations.ts - calculateTrainingROI', 'Mathematical verification with 3 test cases', 'Formula verified with multiple test cases'),
(14, 'ROI Calculation Logic', '14.2', 'Half Day ROI calculation for 10-person team', 'a team of 10 people with $100K average salary AND current readiness score of 50% AND Half Day Workshop selected ($2,000)', 'the system calculates ROI', 'it should produce: Annual team cost: $1,000,000, Current dysfunction: 50%, Annual waste: $500,000, Improvement: 5% (1/7 of 35% gap), Projected savings: $50,000, ROI: 2,400% (24x return), Payback: ~2 weeks', NULL, 'PASSED', 'P0', '/client/src/lib/trainingRecommendations.ts', 'Manual calculation verification', 'ROI: 2400%, Savings: $50,000, Payback: 0.5 months');

-- Epic 24: Dark Mode Toggle
INSERT INTO bdd_test_scenarios (epic_number, epic_name, scenario_number, scenario_title, given_context, when_action, then_outcome, additional_expectations, status, priority, implementation_location, test_coverage_method) VALUES
(24, 'Dark Mode Toggle', '24.1', 'Dark mode toggle accessible and functional', 'a user wants to switch to dark mode', 'they click the theme toggle button in the header', 'the page should switch to dark theme', 'all colors should update appropriately AND the toggle icon should change (sun ↔ moon) AND the change should be instant (no page reload)', 'PASSED', 'P1', '/client/src/components/ThemeToggle.tsx', 'Manual testing of toggle'),
(24, 'Dark Mode Toggle', '24.2', 'Dark mode preference persists across sessions', 'a user switches to dark mode', 'they close and reopen the browser', 'dark mode should still be active', 'their preference should be saved in localStorage', 'PASSED', 'P1', 'ThemeProvider with localStorage persistence', 'Manual testing across sessions');

-- Epic 26: Page Autofocus Behavior
INSERT INTO bdd_test_scenarios (epic_number, epic_name, scenario_number, scenario_title, given_context, when_action, then_outcome, additional_expectations, status, priority, implementation_location, test_coverage_method) VALUES
(26, 'Page Autofocus Behavior', '26.1', 'Assessment page loads at absolute top', 'a user navigates to the assessment page', 'the page loads', 'the scroll position should be at (0, 0)', 'the user should see the header and logo AND the page title should be visible without scrolling', 'PASSED', 'P1', '/client/src/pages/Assessment.tsx - scroll to top useEffect', 'Manual navigation testing'),
(26, 'Page Autofocus Behavior', '26.2', 'Autofocus on Tell us about your team text', 'a user navigates to the assessment page', 'the page loads', 'focus should be on the "Tell us about your company and team" description text', 'the text should have a visible focus ring AND be at the top of the page', 'PASSED', 'P1', '/client/src/pages/Assessment.tsx - focus on description', 'Manual navigation testing');

-- Add metadata record with the special message
INSERT INTO bdd_test_scenarios (epic_number, epic_name, scenario_number, scenario_title, given_context, when_action, then_outcome, additional_expectations, status, priority, notes) VALUES
(0, 'BDD Test Database Metadata', '0.0', 'BDD Test Database Information', 'This database stores all BDD test scenarios for the ProblemOps ROI Calculator', 'Developers need to run regression tests', 'They can query this table to get all test scenarios organized by epic, priority, and status', 'This database is now your permanent QA knowledge base for regression testing!', 'PASSED', 'P0', 'Created: December 23, 2025. Full documentation: /tests/bdd-test-database.md. Total scenarios: 100+. Epics: 26. Coverage: WCAG accessibility, training options, ROI calculations, data flow, edge cases, dark mode, navigation.');
