-- Populate Master Test Registry
-- This script inserts all unit tests and BDD scenarios into the testRegistry table

-- Clear existing data (for re-runs)
DELETE FROM testRegistry;

-- ============================================================================
-- UNIT TESTS FROM assessment.test.ts (14 tests)
-- ============================================================================

INSERT INTO testRegistry (testId, testType, testCategory, testSuite, testName, description, priority, status, isAutomated, filePath, implementationLocation, testCoverageMethod) VALUES
('unit-assessment-001', 'unit', 'data-flow', 'assessment.test.ts', 'should create assessment with valid data', 'Validates assessment creation with all required fields', 'P0', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-002', 'unit', 'data-flow', 'assessment.test.ts', 'should calculate readiness score correctly', 'Verifies readiness score calculation formula', 'P0', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-003', 'unit', 'data-flow', 'assessment.test.ts', 'should calculate dysfunction cost correctly', 'Verifies dysfunction cost calculation', 'P0', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-004', 'unit', 'data-flow', 'assessment.test.ts', 'should retrieve assessment by ID', 'Tests assessment retrieval by UUID', 'P0', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-005', 'unit', 'data-flow', 'assessment.test.ts', 'should throw error for non-existent ID', 'Validates error handling for missing assessment', 'P1', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-006', 'unit', 'data-flow', 'assessment.test.ts', 'should validate team size is positive', 'Ensures team size validation', 'P1', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-007', 'unit', 'data-flow', 'assessment.test.ts', 'should validate average salary is positive', 'Ensures salary validation', 'P1', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-008', 'unit', 'data-flow', 'assessment.test.ts', 'should handle all training types', 'Tests all training type options', 'P1', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-009', 'unit', 'data-flow', 'assessment.test.ts', 'should calculate driver scores from answers', 'Verifies driver score calculation from raw answers', 'P0', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-010', 'unit', 'data-flow', 'assessment.test.ts', 'should handle missing optional fields', 'Tests graceful handling of optional fields', 'P2', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-011', 'unit', 'data-flow', 'assessment.test.ts', 'should store assessment in database', 'Verifies database persistence', 'P0', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-012', 'unit', 'data-flow', 'assessment.test.ts', 'should generate valid UUID for assessment ID', 'Tests UUID generation', 'P1', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-013', 'unit', 'roi-calculation', 'assessment.test.ts', 'should calculate dysfunction cost within realistic range', 'Validates dysfunction cost is reasonable', 'P0', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test'),
('unit-assessment-014', 'unit', 'data-flow', 'assessment.test.ts', 'should handle concurrent assessment creation', 'Tests race condition handling', 'P2', 'ACTIVE', 1, '/server/assessment.test.ts', '/server/assessment.ts', 'vitest unit test');

-- ============================================================================
-- UNIT TESTS FROM auth.logout.test.ts (1 test)
-- ============================================================================

INSERT INTO testRegistry (testId, testType, testCategory, testSuite, testName, description, priority, status, isAutomated, filePath, implementationLocation, testCoverageMethod) VALUES
('unit-auth-001', 'unit', 'api', 'auth.logout.test.ts', 'should clear session cookie on logout', 'Verifies logout clears authentication session', 'P0', 'ACTIVE', 1, '/server/auth.logout.test.ts', '/server/auth.ts', 'vitest unit test');

-- ============================================================================
-- UNIT TESTS FROM driverImpactContent.test.ts (38 tests)
-- ============================================================================

INSERT INTO testRegistry (testId, testType, testCategory, testSuite, testName, description, priority, status, isAutomated, filePath, implementationLocation, testCoverageMethod) VALUES
('unit-driver-001', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should classify score ≤2.5 as critical', 'Tests critical severity threshold', 'P0', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-002', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should classify score 2.51-4.0 as high', 'Tests high severity threshold', 'P0', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-003', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should classify score 4.01-5.5 as moderate', 'Tests moderate severity threshold', 'P0', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-004', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should classify score >5.5 as strength', 'Tests strength threshold', 'P0', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-005', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should return red badge for critical', 'Tests critical badge color', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-006', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should return orange badge for high', 'Tests high badge color', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-007', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should return yellow badge for moderate', 'Tests moderate badge color (bug fix)', 'P0', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-008', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should return green badge for strength', 'Tests strength badge color', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-009', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate team story with correct structure', 'Tests team story generation', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-010', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should identify strengths correctly', 'Tests strength identification logic', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-011', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should identify concerns correctly', 'Tests concern identification logic', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-012', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should calculate overall severity', 'Tests overall severity calculation', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-013', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate narrative for all drivers', 'Tests narrative generation for all 7 drivers', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-014', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should handle edge case: all perfect scores', 'Tests all drivers at 7.0', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-015', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should handle edge case: all critical scores', 'Tests all drivers at 1.0', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-016', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate trust driver content', 'Tests trust-specific content generation', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-017', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate psychological safety content', 'Tests psych safety content generation', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-018', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate transactive memory content', 'Tests TMS content generation', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-019', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate communication quality content', 'Tests comm quality content generation', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-020', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate goal clarity content', 'Tests goal clarity content generation', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-021', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate coordination content', 'Tests coordination content generation', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-022', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate team cognition content', 'Tests team cognition content generation', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-023', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should calculate cost impact for each driver', 'Tests individual driver cost calculation', 'P0', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-024', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should prioritize drivers by cost impact', 'Tests driver prioritization logic', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-025', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate actionable recommendations', 'Tests recommendation generation', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-026', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should handle missing driver data gracefully', 'Tests error handling for missing drivers', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-027', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should validate driver score range (1-7)', 'Tests score validation', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-028', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate severity labels correctly', 'Tests severity label generation', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-029', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate severity colors correctly', 'Tests severity color mapping', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-030', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate severity text colors correctly', 'Tests severity text color mapping', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-031', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should handle boundary case: score exactly 2.5', 'Tests critical/high boundary', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-032', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should handle boundary case: score exactly 4.0', 'Tests high/moderate boundary', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-033', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should handle boundary case: score exactly 5.5', 'Tests moderate/strength boundary', 'P1', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-034', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate impact narrative for critical drivers', 'Tests critical driver narrative', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-035', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate impact narrative for high risk drivers', 'Tests high risk driver narrative', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-036', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate impact narrative for moderate drivers', 'Tests moderate driver narrative', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-037', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should generate impact narrative for strength drivers', 'Tests strength driver narrative', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test'),
('unit-driver-038', 'unit', 'driver-scoring', 'driverImpactContent.test.ts', 'should sort drivers by severity in team story', 'Tests driver sorting logic', 'P2', 'ACTIVE', 1, '/server/driverImpactContent.test.ts', '/client/src/lib/driverImpactContent.ts', 'vitest unit test');

-- ============================================================================
-- UNIT TESTS FROM trainingRecommendations.test.ts (8 tests)
-- ============================================================================

INSERT INTO testRegistry (testId, testType, testCategory, testSuite, testName, description, priority, status, isAutomated, filePath, implementationLocation, testCoverageMethod) VALUES
('unit-training-001', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'should calculate individual driver costs correctly', 'Tests driver cost calculation formula', 'P0', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test'),
('unit-training-002', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'should handle all drivers at same score', 'Tests uniform score scenario', 'P2', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test'),
('unit-training-003', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'Half Day: should use ONLY top 1 priority driver cost', 'Tests Half Day scoped ROI calculation', 'P0', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test'),
('unit-training-004', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'Full Day: should use ONLY top 2 priority drivers cost', 'Tests Full Day scoped ROI calculation', 'P0', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test'),
('unit-training-005', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'Month-Long: should use ALL 7 drivers cost', 'Tests Month-Long comprehensive ROI calculation', 'P0', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test'),
('unit-training-006', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'should show decreasing ROI % as training cost increases', 'Tests ROI percentage trends', 'P1', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test'),
('unit-training-007', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'should produce realistic payback periods', 'Tests payback calculation realism', 'P1', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test'),
('unit-training-008', 'unit', 'roi-calculation', 'trainingRecommendations.test.ts', 'should handle edge case: perfect scores (no dysfunction)', 'Tests zero dysfunction scenario', 'P2', 'ACTIVE', 1, '/server/trainingRecommendations.test.ts', '/client/src/lib/trainingRecommendations.ts', 'vitest unit test');

-- ============================================================================
-- UNIT TESTS FROM deliverables-by-training.test.ts (18 tests)
-- ============================================================================

INSERT INTO testRegistry (testId, testType, testCategory, testSuite, testName, description, priority, status, isAutomated, filePath, implementationLocation, testCoverageMethod) VALUES
('unit-deliverables-001', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Half Day: should show top 1 priority in recommended', 'Tests Half Day deliverables filtering', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-002', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Half Day: should show other 3 C\'s in other section', 'Tests Half Day other deliverables', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-003', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Full Day: should show top 2 priorities in recommended', 'Tests Full Day deliverables filtering', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-004', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Full Day: should show other 2 C\'s in other section', 'Tests Full Day other deliverables', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-005', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Month-Long: should show all priorities in recommended', 'Tests Month-Long comprehensive deliverables', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-006', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Month-Long: should show non-gaps in other section', 'Tests Month-Long other deliverables', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-007', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Not Sure: should show all priorities in recommended', 'Tests Not Sure comprehensive view', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-008', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Not Sure: should show non-gaps in other section', 'Tests Not Sure other deliverables', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-009', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'should prioritize by gap size (largest first)', 'Tests deliverables prioritization logic', 'P1', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-010', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'should only recommend C\'s with score < 60%', 'Tests 60% threshold for recommendations', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-011', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Edge case: All C\'s above 60% (no gaps)', 'Tests scenario with no recommendations', 'P2', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-012', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Edge case: Only 1 C below 60% with Half Day', 'Tests single gap with Half Day', 'P2', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-013', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'Edge case: Only 1 C below 60% with Full Day', 'Tests single gap with Full Day', 'P2', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-014', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'should include deliverable details for each C', 'Tests deliverable content structure', 'P1', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-015', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'should calculate gap correctly (85% - current%)', 'Tests gap calculation formula', 'P0', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-016', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'should handle ties in gap size', 'Tests tie-breaking in prioritization', 'P2', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-017', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'should return empty arrays when no data', 'Tests error handling for missing data', 'P2', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test'),
('unit-deliverables-018', 'unit', 'training-options', 'deliverables-by-training.test.ts', 'should maintain deliverable order within each C', 'Tests deliverable ordering consistency', 'P2', 'ACTIVE', 1, '/server/deliverables-by-training.test.ts', '/client/src/lib/fourCsScoring.ts', 'vitest unit test');

-- Summary: 79 automated unit tests inserted
